# day05 【异常、线程】

## 主要内容  

- 异常（提高程序的健壮性的，它是每个系统都会出现的问题）
-  软件是没有完美的，都可能出现异常。异常是需要提前避免，但是可能又无法绝对避免，所以需要提前做异常处理机制。
  - 概念
  - 体系
  - 处理方式
- 多线程

## 教学目标

- [ ] 能够辨别程序中异常和错误的区别
- [ ] 说出异常的分类
- [ ] 说出虚拟机处理异常的方式
- [ ] 列举出常见的三个运行期异常
- [ ] 能够使用try...catch关键字处理异常
- [ ] 能够使用throws关键字处理异常
- [ ] 能够自定义异常类
- [ ] 能够处理自定义异常类
- [ ] 说出进程的概念
- [ ] 说出线程的概念
- [ ] 能够理解并发与并行的区别
- [ ] 能够开启新线程

# 第一章    异常概述

## 1.1 异常概述

### 1.1 .1 异常的概念

- 程序在编译或运行过程中出现的问题则称为异常。

### 1.1.2 异常的分类

- 编译时异常
- 运行时异常

### 1.1.3 异常的继承体系

![](/Users/pkxing/Documents/88期就业班/就业班-day05-异常、线程/笔记/异常继承体系图.png)

## 1.2 Throwable常用方法 

```jav
* void	printStackTrace() 打印异常的栈信息(追踪异常产生的根源)
* String  getMessage() 获得异常信息字符串
* String  toString() 获得异常详细信息：类全名+异常信息字符串
```

- 示例代码

```java
public class ThrowableDemo {
    public static void main(String[] args){
        test02();
    }

    private static void test02() {
        test01();
    }

    private static void test01() {
        // 创建Throwable对象(异常对象)
        Throwable t = new Throwable("哎...出问题了");
        //  打印异常的栈信息(
        // t.printStackTrace();

        // 获得异常信息字符串
        // 哎...出问题了
        // System.out.println(t.getMessage());

        // java.lang.Throwable: 哎...出问题了
        System.out.println(t.toString());
    }
}
```

### 1.3 异常和错误的区别

![](/Users/pkxing/Documents/88期就业班/就业班-day05-异常、线程/笔记/异常和错误的区别.png)

### 1.4 异常的产生过程分析

![](/Users/pkxing/Documents/88期就业班/就业班-day05-异常、线程/笔记/异常产生过程分析.png)

# 第二章 异常的处理

## 2.1 JVM处理方式

```java
JVM处理方式
    * 将异常信息(异常类名，异常的原因，异常位置)打印在控制台
    * 退出JVM，终止程序的运行。
```

## 2.2  捕获异常try…catch

~~~java
try{
     编写可能会出现异常的代码
}catch(异常类型  e){
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}
~~~

**try：**该代码块中编写可能产生异常的代码。

**catch：**用来进行某种异常的捕获，实现对捕获到的异常进行处理。

> 注意:try和catch都不能单独使用,必须连用。

**捕获异常示例演示：**

~~~java
/**
    单catch捕获处理异常的格式
     try{

    } catch(异常类名  变量名){

    }
    说明
        try代码块
            * 编写可能会出现异常的代码,如果该代码块中的某行代码出现了异常
                 则try代码块后续的代码不会被执行了
        catch代码块：
            * 编写处理异常的代码，如果try代码块中的代码没有出现异常
                则catch代码块的代码不会被执行。
 */
public class ExceptionDemo02 {
    public static void main(String[] args){
        int a = 0;
        test(a);
    }

    private static void test(int a) {
        try{
            /*
            1.创建一个对象：ArithmeticException ee = new ArithmeticException("/ by zero");
            2.抛出异常对象：ee
            */
            int result = 100 / a;
            System.out.println("result = " + result); // 50
        }catch (ArithmeticException e){ // e = ee;
            System.out.println("进来了吗");
            // 在调式阶段，一般都会调用该方法打印异常信息
            e.printStackTrace();
        }
        System.out.println("come here");
    }
}
~~~

多个异常使用捕获又该如何处理呢？

1. 多个异常分别处理。
2. 多个异常一次捕获，多次处理。
3. 多个异常一次捕获一次处理。

一般我们是使用一次捕获多次处理方式，格式如下：

~~~java
try{
     编写可能会出现异常的代码
}catch(异常类型A  e){  当try中出现A类型异常,就用该catch来捕获.
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}catch(异常类型B  e){  当try中出现B类型异常,就用该catch来捕获.
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}
~~~

- 多catch处理异常示例代码

```java
/**
    多catch捕获处理异常的格式
     try{

     } catch(异常类名  变量名){

     } catch(异常类名  变量名){

     } ...catch(异常类名  变量名){

     }
     
    说明
        try代码块
            * 编写可能会出现异常的代码,如果该代码块中的某行代码出现了异常
                 则try代码块后续的代码不会被执行了
        catch代码块：
            * 编写处理异常的代码，如果try代码块中的代码没有出现异常
                则catch代码块的代码不会被执行。
 */
public class ExceptionDemo03 {
    public static void main(String[] args){
        int a = 2;
        test(a);
    }

    private static void test(int a) {
        try{
            /*
            1.创建一个对象：ArithmeticException ee = new ArithmeticException("/ by zero");
            2.抛出异常对象：ee
            */
            int result = 100 / a;
            System.out.println("result = " + result); // 50

            // 定义字符串
            String str = "abc";
            /*
                1.创建一个对象：NullPointerException ee = new NullPointerException();
                2.抛出异常对象：ee
             */
            System.out.println(str.length()); // 3

            // 定义一个数组
            int[] arr = {1,2,3};
            /*
                1.创建一个对象：ArrayIndexOutOfBoundsException ee = new ArrayIndexOutOfBoundsException("3");
                2.抛出异常对象：ee
             */
            System.out.println(arr[2]); // 3

            System.out.println(str.charAt(4));

        } catch (NullPointerException e){ // e = new NullPointerException();
            System.out.println("又进来了吗");
        } catch (ArithmeticException e){ // e = new ArithmeticException("/ by zero");
            System.out.println("进来了吗");
        }  catch (ArrayIndexOutOfBoundsException e){
            System.out.println("又又进来了吗");
        } catch (Exception e){ // e = new StringIndexOutOfBounds("");
            System.out.println("又又又进来了吗");
        }
        System.out.println("come here");
    }
}
```

- 多catch捕获处理注意事项

```java
try代码块中不可能同时出现两个异常，多个catch代码块不可能同时执行两个。
多个异常类名之间有继承关系，则父类类型要放在子类类型下面
多个异常类名之间没有继承关系，则没有顺序要求。
```

## 2.3 抛出异常throw和声明异常throws

```java
throw关键字作用
    * 用来抛出异常对象，将异常对象抛给方法调用者，并结束当前方法的运行。

throw关键字使用格式
    * throw 异常对象;

throw关键字的使用位置：使用在方法体中

throws关键字作用
    * 用来声明异常，告诉方法调用者方法可能会出现的异常有哪些，让调用者对异常进行处理。

throws关键字使用格式
    * 修饰符 返回值类型  方法名(参数列表)throws 异常类名,... {}

throws关键字的使用位置：使用在方法声明上
```

- 示例代码

```java
public class ExceptionDemo05 {
    public static void main(String[] args){
        int a = 0;
        test(a);
    }

    private static void test(int a) throws ArithmeticException,NullPointerException {
        /*
            1. 创建异常对象：ArithmeticException e new ArithmeticException("/ by zero");
            2. 抛出异常对象：throw e;
         */
        if(a == 0){
            // 创建异常对象
            ArithmeticException e = new ArithmeticException("除数不能为零");
            // 抛出异常对象
            throw e;
        }
        int result = 100 / a ;
        System.out.println("result = " + result);
        System.out.println("come here");
    }
}
```

## 2.4 finally 代码块

```java
finally代码块的特点
    * 只要代码执行流程进入了try代码块，不管是否出现异常，该代码块中的代码都会执行。

finally代码块的作用
    * 用来释放资源，比如关闭流，关闭数据库资源

捕获处理的完整格式
 try{

 } catch(异常类名  变量名){

 } finally{

 }
```

- 示例代码

```java
public class ExceptionDemo04 {
    public static void main(String[] args){
        int a = 2;
        System.out.println(test(a));
    }

    private static int test(int a) {
        if (a != 0){
            try{
                /*
                1.创建一个对象：ArithmeticException ee = new ArithmeticException("/ by zero");
                2.抛出异常对象：ee
                */
                int result = 100 / a;
                System.out.println("result = " + result); // 50
                // 退出JVM，终止程序运行，不会执行finally代码块了
                System.exit(0);
                return 200;
            } catch (Exception e){
                System.out.println("进来了吗");
            } finally {
                System.out.println("释放资源");
            }
        }
        System.out.println("come here");
        return 100;
    }
}
```

## 2.6  方法重写异常处理注意点

```java
方法重写时异常处理注意事项(针对编译时异常)
    * 子类重写方法时声明的异常不能大于父类方法声明的异常。
```

## 2.7 编译时异常和运行时异常

```java
编译时异常的概念
    * 除了运行时异常以为的所有的异常都是编译时异常。

运行时异常的概念
    * 只要是RuntimeException或RuntimeException的子类异常都属于运行时异常。

运行时异常的特点
    * 方法体中如果抛出的异常是运行时异常，则可以处理，也可以处理。
    * 方法声明上声明的异常如果是运行时异常，则方法调用者可以处理，也可以不处理。

编译时异常的特点
    * 方法体中如果抛出的异常是编译时异常，则要求必须要处理
    * 方法声明上声明的异常如果是编译时异常，则要求调用者一定要处理。

为什么java编译器对运行时异常管理如此松散？
    * 因为运行时异常一般是可以通过程序猿良好的编程习惯避免。
```

# 第三章 自定义异常

## 3.1 概述

**为什么需要自定义异常类:**

我们说了Java中不同的异常类,分别表示着某一种具体的异常情况,那么在开发中总是有些异常情况是SUN没有定义好的,此时我们根据自己业务的异常情况来定义异常类。,例如年龄负数问题,考试成绩负数问题。

在上述代码中，发现这些异常都是JDK内部定义好的，但是实际开发中也会出现很多异常,这些异常很可能在JDK中没有定义过,例如年龄负数问题,考试成绩负数问题.那么能不能自己定义异常呢？

**异常类如何定义:**

1. 自定义一个编译期异常: 自定义类 并继承于`java.lang.Exception`。
2. 自定义一个运行时期的异常类:自定义类 并继承于`java.lang.RuntimeException`。

## 3.2 自定义异常的练习

1. 在Person类的有参数构造方法中，进行年龄范围的判断。
2. 若年龄为负数或大于200岁，则抛出NoAgeException异常，异常提示信息“年龄数值非法”。
3. 要求：在测试类中，调用有参数构造方法，完成Person对象创建，并进行异常的处理。

首先定义一个登陆异常类NoAgeException：

~~~java
public class NoAgeException extends /* RuntimeException */ Exception {
    // 无参数构造方法
    public NoAgeException(){
		  		     
    }

    // 有参数构造方法
    public NoAgeException(String message){
        super(message);
    }
}
~~~

再定义Person类，在setAge方法判断传入年龄是否合法，如果不合法则抛出自定义异常并提示：**你不是地球人，滚回火星去**

~~~java
public class Person {
    private int age;

    public Person(int age) throws NoAgeException{
        setAge(age);
    }

    public Person() {
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) throws NoAgeException{
        // 判断age是否大于0并小于200
        if (age < 0 || age > 200){
            // 抛出异常：年龄值非法
            throw new NoAgeException("年龄值非法");
        }
        this.age = age;
    }

    @Override
    public String toString() {
        return "Person{" +
                "age=" + age +
                '}';
    }
}
~~~

最后创建测试类，代码如下

```java
public class ExceptionDemo01 {
    public static void main(String[] args){
       /* NoAgeException e = new NoAgeException("年龄值非法");
        System.out.println(e.getMessage());*/
       try{
           // 创建Person对象
           Person p = new Person(400);
           // 调用set方法修改年龄
           p.setAge(300);
           System.out.println("p = " + p );
       }catch (NoAgeException e){

       }
    }
}

```

#  第四章 多线程

## 4.1 并发与并行

```java
并行和并发的概念
    并行：两个任务在同一时间点执行。比如 A任务:12:29:30  B任务：12:29:30  称为并行执行
    并发：两个任务在同一个时间段内执行。比如 在12:29:30 到 12:35:30 执行了任务A和任务B，则称为并发执行。
```

## 4.2 线程与进程

```java
什么是进程
    * 正在运行中的一个程序则称为进程。

什么是线程
    * 是进程中的一个独立的执行路径。

进程和线程的案例
    * 工厂：可以理解进程
    * 工人：可以理解线程

进程和线程的作用
    * 线程：负责执行代码的。
    * 进程：用来封装线程的，并为线程执行任务提供资源：内存资源。
```

## 4.3 创建线程类

```java
/**
自定义线程类
 */
public class MyThread extends Thread {

    @Override
    public void run() {
        System.out.println("线程任务");
        for (int i = 0; i < 10 ; i++) {
            System.out.println("run = " + i);
        }
    }
}

public class ThreadDemo01 {
    public static void main(String[] args){
        // System.out.println("abc");
        // 创建线程对象：招了一个工人
        MyThread t = new MyThread();
        // 开启线程：让工人干活
        t.start();

        for (int i = 0; i < 10 ; i++) {
            System.out.println("main = " + i);
        }
        // 不要直接调用run方法，直接调用不会开启新的执行路径
        // t.run();
    }
}
```

# 第五章 小结

```java
异常处理小结
    什么是异常：程序在编译或运行过程中出现的问题。
    什么是错误：程序在运行过程中出现的问题。

异常和错误的区别
    * 如果类名是以Error结尾是错误，错误只能修改代码，否则无法继续运行。
    * 如果类名是以Exception结尾是异常，异常有特定处理方法，如果不处理，则程序无法继承运行。

异常的继承体系
    * Throwable：是所有错误和异常的父类。
        * Error：错误
        * Exception：异常

异常的分类
    * 编译时异常
        * 方法声明上声明了编译时异常，则要求调用者一定要处理
        * 方法体中抛出编译时异常，则要求一定要处理(可以自己处理，也可以声明处理)
    * 运行时异常
        * 方法声明上声明了运行时异常，则方法调用者可以处理，也可以不处理。
        * 方法体中抛出运行时异常，则可以处理，也可以不处理。

异常的处理方式
    * JVM处理方式：将异常信息输出到控制台，结束程序运行。
    * 手动处理方式

捕获处理格式
    try{
        // 可能出现异常的代码
    } catch(异常类名 变量名){
        // 处理异常代码
    } ...
    finally{
        // 最终要执行的代码.释放资源
    }

抛出处理方式
    * throw和throws关键字的作用
        * throw：用来抛出异常对象，将异常对象跑给方法调用者，并结束当前方法的运行。
        * throws：用来声明异常，将异常标识处理告诉方法调用者，让方法调用者处理异常。

    * throw和throws关键字使用位置和格式
        * throw：方法体中，格式： throw 异常对象;
        * throws：方法声明中 格式：方法声明 throws 异常类名,....{}

方法重写时注意事项(针对编译时异常)
    * 子类重写方法时不能抛出比父类声明大的异常。
```

